### ISSUE TITLE
IdentifiableTypeImpl fails to retrieve PK information from MappedSuperClass when using GENERICS

### ISSUE THREAD

**Issue by mkolesnikov** [datanucleus/datanucleus-api-jpa#26]
Here are domains classes:
```java
@MappedSuperclass
public abstract class BaseEntity<ID extends Serializable> {
  @Id
  @Column(name = ID)
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQ_GEN)
  @SequenceGenerator(name = SEQ_GEN, allocationSize = 1)
  private ID id;

...
}

@Entity
public class Note extends BaseEntity<Long> {

}
```
Getting exception:
```
Caused by: java.lang.IllegalArgumentException: PK member is not of specified type (java.lang.Long). Should be java.io.Serializable
    at org.datanucleus.api.jpa.metamodel.IdentifiableTypeImpl.getId(IdentifiableTypeImpl.java:102)
    at org.datanucleus.api.jpa.metamodel.IdentifiableTypeImpl.getId(IdentifiableTypeImpl.java:79)
    at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation$IdMetadata.<init>(JpaMetamodelEntityInformation.java:249)
```
IdentifiableTypeImpl.java
```java
public <Y> SingularAttribute<? super X, Y> getId(Class<Y> cls)
{
...
        int pkPosition = cmd.getPKMemberPositions()[0];
        AbstractMemberMetaData mmd = cmd.getMetaDataForManagedMemberAtAbsolutePosition(pkPosition);

        // *BUG*: We come here with supertype, 
        // thus, it should be mmd.getType().isAssignableFrom(cls)
        if (cls.isAssignableFrom(mmd.getType()))
        {
            // User passed in the type of the field
            SingularAttribute attr = (SingularAttribute) attributes.get(mmd.getName());
            if (attr == null)
            {
                IdentifiableType supertype = getSupertype();
                if (supertype != null)
                {
                    // Relay to the supertype
                    return supertype.getId(cls);
                }
            }
            return attr;
        }
...
}
```

**Comment by andyjefferson** [comment]
Testcases are defined by http://www.datanucleus.org/documentation/problem_reporting.html as the issue template said

**Comment by andyjefferson** [comment]
Closing since no testcase provided. Attach a testcase here and it can be reopened.

**Comment by mkolesnikov** [comment]
https://github.com/mkolesnikov/spring-data-datanucleus
See `PersionRepositoryTest`

**Comment by andyjefferson** [comment]
Please follow the Problem Reporting link that was provided above. There is no SPRING in our template and it is not essential for anything.

**Comment by mkolesnikov** [comment]
Okay, here is another one https://github.com/mkolesnikov/datanucleus-test-jap
See `IdentifiableTypeImplTest`, now it's pure initial test-jpa project. I thought that it's obvious issue that derived class is not assignable from parent class.

**Comment by andyjefferson** [comment]
Thanks for the test (though it is buggy itself ... should use e.getIdType().getJavaType()).
