### ISSUE TITLE
NPE in IdentifiableTypeImpl.getSupertype

### ISSUE THREAD

**Issue by ayakovlevgh** [datanucleus/datanucleus-api-jpa#39]
After the tickets #27 #29 were fixed the NPE occurs when IdentifiableTypeImpl.getSupertype is invoked:

```
java.lang.NullPointerException
	at org.datanucleus.api.jpa.metamodel.IdentifiableTypeImpl.getSupertype(IdentifiableTypeImpl.java:157)
	at org.datanucleus.api.jpa.metamodel.IdentifiableTypeImpl.getVersion(IdentifiableTypeImpl.java:188)
```
Because of this Spring Data JPA does not work:
```
[INFO] java.lang.NullPointerException
[INFO] 	at org.datanucleus.api.jpa.metamodel.IdentifiableTypeImpl.getSupertype(IdentifiableTypeImpl.java:157)
[INFO] 	at org.datanucleus.api.jpa.metamodel.IdentifiableTypeImpl.getVersion(IdentifiableTypeImpl.java:188)
[INFO] 	at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation.findVersionAttribute(JpaMetamodelEntityInformation.java:107)
[INFO] 	at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation.<init>(JpaMetamodelEntityInformation.java:83)
[INFO] 	at org.springframework.data.jpa.repository.support.JpaEntityInformationSupport.getEntityInformation(JpaEntityInformationSupport.java:67)
[INFO] 	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getEntityInformation(JpaRepositoryFactory.java:152)
[INFO] 	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:99)
[INFO] 	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:81)
[INFO] 	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:199)
[INFO] 	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:266)
[INFO] 	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:252)
[INFO] 	at org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:92)
```

datanucleus-api-jpa version: 4.1.11
datanucleus-core version: 4.1.12

Here is a test case:
https://github.com/ayakovlevgh/test-jpa/tree/4.1

**Comment by andyjefferson** [comment]
So provide a GitHub PULL REQUEST. That is by far the quicker way to develop code.

**Comment by ayakovlevgh** [comment]
Actually assuming how many bugs we've already faced while using Datanucleus, I believe it is better to move our project to Hibernate / EclipseLink.

**Comment by andyjefferson** [comment]
Whatever. User, when asked to contribute, can't be bothered. 
Good luck on using projects that are less willing to accept input than we are, and have long open bug lists.
