### ISSUE TITLE
JPA Converter not working

### ISSUE THREAD

**Issue by javaone199** [datanucleus/datanucleus-api-jpa#96]
JPA Converter not working

https://stackoverflow.com/questions/45739114/datanucleus-type-converter-jpa-2-1-compliant/45739172?noredirect=1#comment78437190_45739172

@Converter(autoApply=true)
public class FooConverter implements AttributeConverter<Foo, String> {

    @Override
    public String convertToDatabaseColumn(Foo attribute) {
                ....
    }

    @Override
    public Foo convertToEntityAttribute(String value) {
        ...
    }

}

@Entity
public class Bar {

      @Convert(converter=FooConverter.class) 
      public Foo getFoo() {
           ...
      }

      public void setFoo(Foo foo) {
           ...
      }

}

Error:

org.datanucleus.exceptions.NucleusUserException: Identifier hello.world is unresolved (not a static field)
        at org.datanucleus.query.expression.PrimaryExpression.bind(PrimaryExpression.java:215)
        at org.datanucleus.query.expression.DyadicExpression.bind(DyadicExpression.java:131)
        at org.datanucleus.query.expression.DyadicExpression.bind(DyadicExpression.java:131)
        at org.datanucleus.query.expression.DyadicExpression.bind(DyadicExpression.java:89)
        at org.datanucleus.query.compiler.JavaQueryCompiler.compileFilter(JavaQueryCompiler.java:617)
        at org.datanucleus.query.compiler.JPQLCompiler.compile(JPQLCompiler.java:86)
        at org.datanucleus.store.query.AbstractJPQLQuery.compileGeneric(AbstractJPQLQuery.java:304)
        at org.datanucleus.store.query.AbstractJPQLQuery.compileInternal(AbstractJPQLQuery.java:365)
The 'hello.world' in error message is the string value of Foo.

It seems that the converter is ignored.

**Comment by javaone199** [comment]
The same code works for EclipseLink.

**Comment by andyjefferson** [comment]
Kindly provide a valid testcase as per what the reporting template tells you. Here it is one more time http://www.datanucleus.org/documentation/problem_reporting.html#jpa

**Comment by javaone199** [comment]
Does datanucleus has a test case for AttributeConverter/@Converter? I would like to have a quick check before making a new test case.

**Comment by andyjefferson** [comment]
PUBLIC Repository "tests" has jpa/general and contains tests for AttributeConverter.

**Comment by javaone199** [comment]
The issue is in processing literal(Object)

CriteriaBuilder cb = em.getCriteriaBuilder();
CriteriaQuery<Bar> query = cb.createQuery(Bar.class);
Root<Bar> root = query.from(Bar.class);
Foo foo = new Foo("hello", "world");
query.where(cb.eq(root.get("foo"),  cb.literal(foo)));
TypedQuery<Bar> typedQuery = em.createQuery(query);
List<Bar> results = typedQuery.getResultList();

From debugging, the literal(Foo) is converted to string using Foo.toString() in getting jpqlString, ignoring the FooConverter.  JPA literal can be any user defined object, and converter should be used if defined.

**Comment by andyjefferson** [comment]
Converters are used in many places and their MAIN USE-CASE is for PERSISTENCE, not QUERYING. There are queries in the AttributeConverter tests (just not Criteria type). Define a JPQL query. Criteria queries themselves are tested in the "jpa/criteria" project

**Comment by javaone199** [comment]
Request to reopen this issue. Datanucleus is not able to handle literal(userDefinedObject_with_converter) in CriteriaQuery as the example above.

**Comment by andyjefferson** [comment]
So attach a testcase as per how the documentation requests
